/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as LotoRouteImport } from './routes/loto'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PermitsPermitIdRouteImport } from './routes/permits.$permitId'
import { Route as PermitsNewRouteImport } from './routes/permits.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const LotoRoute = LotoRouteImport.update({
  id: '/loto',
  path: '/loto',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsPermitIdRoute = PermitsPermitIdRouteImport.update({
  id: '/permits/$permitId',
  path: '/permits/$permitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsNewRoute = PermitsNewRouteImport.update({
  id: '/permits/new',
  path: '/permits/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/loto': typeof LotoRoute
  '/settings': typeof SettingsRoute
  '/permits/$permitId': typeof PermitsPermitIdRoute
  '/permits/new': typeof PermitsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/loto': typeof LotoRoute
  '/settings': typeof SettingsRoute
  '/permits/$permitId': typeof PermitsPermitIdRoute
  '/permits/new': typeof PermitsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/loto': typeof LotoRoute
  '/settings': typeof SettingsRoute
  '/permits/$permitId': typeof PermitsPermitIdRoute
  '/permits/new': typeof PermitsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/loto'
    | '/settings'
    | '/permits/$permitId'
    | '/permits/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/loto'
    | '/settings'
    | '/permits/$permitId'
    | '/permits/new'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/loto'
    | '/settings'
    | '/permits/$permitId'
    | '/permits/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  LotoRoute: typeof LotoRoute
  SettingsRoute: typeof SettingsRoute
  PermitsPermitIdRoute: typeof PermitsPermitIdRoute
  PermitsNewRoute: typeof PermitsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loto': {
      id: '/loto'
      path: '/loto'
      fullPath: '/loto'
      preLoaderRoute: typeof LotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/$permitId': {
      id: '/permits/$permitId'
      path: '/permits/$permitId'
      fullPath: '/permits/$permitId'
      preLoaderRoute: typeof PermitsPermitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits/new': {
      id: '/permits/new'
      path: '/permits/new'
      fullPath: '/permits/new'
      preLoaderRoute: typeof PermitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  LotoRoute: LotoRoute,
  SettingsRoute: SettingsRoute,
  PermitsPermitIdRoute: PermitsPermitIdRoute,
  PermitsNewRoute: PermitsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
